### PR TITLE
Refactor into Class files

### PR DESCRIPTION
**Pull request by northcott-j**
*Very much a work in progress*

Wanted to push what I had to get some feedback. I've highlighted things I need to work on in the README. I'm just learning Ruby, and your project looked like something super cool to mess around with to try to get the hang of it.

This currently introduces a regression in performance. My dataset was 1.6GB and the processing time for ingesting messages became much slower. I'm planning on doing a Flame graph to find out where the bottleneck is. This refactor also increases memory usage as I segment message data in several ways with the intention of adding more totals and breakdowns. 

Ideas behind the design:
- I wanted to make it easier for people to make new classes and easily add them to the output spreadsheet
- consolidate related code into a single place
- make it easier to potentially use the Parallel library to speed things up

### CODE REVIEW

**Comment by northcott-j** [comment]
edit: realizing now that there's another PR open that started the refactor. I'll see what I can merge and to break things down into more manageable chunks

**Comment by Lackoftactics** [comment]
ok, I will try to first merge first one and then you can adjust. I like that you broke down into files 👍

**Comment by Lackoftactics** [comment]
@northcott-j I got also error thrown when trying your PR

```
Analyzing conversation with: 
/Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/message.rb:16:in `initialize': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:54:in `new'
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:54:in `block (3 levels) in analyze'
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:50:in `each'
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:50:in `block (2 levels) in analyze'
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:38:in `each'
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:38:in `block in analyze'
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:35:in `chdir'
	from /Users/przemyslawmroczek/Projects/analyze_facebook_data/classes/analyzeables/messages.rb:35:in `analyze'
	from analyze_facebook_data.rb:44:in `block in <main>'
	from analyze_facebook_data.rb:43:in `each'
	from analyze_facebook_data.rb:43:in `<main>'
```

**Comment by northcott-j** [comment]
@Lackoftactics I added a line `next if sender.nil?` that will hopefully fix the error that you're getting. I'll keep working on improving performance and cleaning things up

**Comment by Lackoftactics** [comment]
as @MetricMike and @thnukid created good case for breaking files, I merged their PR and you can later refactor that. Closing this PR

**Pull request closed without merging**
